version: "3.3"
services:
  harperdb:
    image: harperdb/hdb
    volumes:
      - harperdb_hdb:/opt/HarperDB/hdb
    ports:
      - "9925:9925"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9925"]
      interval: 10m
      timeout: 10s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: unless-stopped
    
  getKentikInterfaces:
    build:
      context: .
      args:
        - KENTIK_URL=${KENTIK_URL}
        - KENTIK_API_USER=${KENTIK_API_USER}
        - KENTIK_API_TOKEN=${KENTIK_API_TOKEN}
        - KENTIK_HARPERDB_URL=${KENTIK_HARPERDB_URL}
        - KENTIK_HARPERDB_USER=${KENTIK_HARPERDB_USER}
        - KENTIK_HARPERDB_PASSWORD=${KENTIK_HARPERDB_PASSWORD}
        - KENTIK_HARPERDB_SCHEMA=${KENTIK_HARPERDB_SCHEMA}
        - KENTIK_HARPERDB_TABLE=${KENTIK_HARPERDB_TABLE}
        - KENTIK_QUERY_TIME_INCROMENT=${KENTIK_QUERY_TIME_INCROMENT}
        - KENTIK_QUERY_TIME_AMOUNT=${KENTIK_QUERY_TIME_AMOUNT}
    image: kentik/getKentikInterfaces
    environment:
        - KENTIK_URL=${KENTIK_URL}
        - KENTIK_API_USER=${KENTIK_API_USER}
        - KENTIK_API_TOKEN=${KENTIK_API_TOKEN}
        - KENTIK_HARPERDB_URL=${KENTIK_HARPERDB_URL}
        - KENTIK_HARPERDB_USER=${KENTIK_HARPERDB_USER}
        - KENTIK_HARPERDB_PASSWORD=${KENTIK_HARPERDB_PASSWORD}
        - KENTIK_HARPERDB_SCHEMA=${KENTIK_HARPERDB_SCHEMA}
        - KENTIK_HARPERDB_TABLE=${KENTIK_HARPERDB_TABLE}
        - KENTIK_QUERY_TIME_INCROMENT=${KENTIK_QUERY_TIME_INCROMENT}
        - KENTIK_QUERY_TIME_AMOUNT=${KENTIK_QUERY_TIME_AMOUNT}
    depends_on:
      - "harperdb"