version: "3.3"
services:
  harperdb:
    image: harperdb/hdb
    volumes:
      - harperdb_hdb:/opt/HarperDB/hdb
    ports:
      - "9925:9925"
    networks:
      - kentik
    labels:
      com.kentik.deployment: poc
      com.kentik.disc: "Recuring Get Inteface Metrics From Kentik"
      com.kentik.type: "pull data"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9925"]
      interval: 5m
      timeout: 10s
      retries: 6
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: unless-stopped 
    
  setupHarper:
    build:
      context: .
    image: kentik/harperSetup
    networks:
      - kentik
    secrets:
      - harperdb
    labels:
      com.kentik.deployment: poc
      com.kentik.disc: "Check if harper needs to be setup"
      com.kentik.type: "Check"
    environment:
        - KENTIK_HARPERDB_URL=${KENTIK_HARPERDB_URL}
        - KENTIK_HARPERDB_SCHEMA=${KENTIK_HARPERDB_SCHEMA}
        - KENTIK_HARPERDB_TABLE=${KENTIK_HARPERDB_TABLE}
    command: ['python', './harperDBSetup.py', '--harperdb_url=$KENTIK_HARPERDB_URL', '--harperdb_schema=$KENTIK_HARPERDB_SCHEMA', '--harperdb_table=$KENTIK_HARPERDB_TABLE']
    depends_on:
      - "harperdb"
    
  getKentikInterfaces:
    build:
      context: .
    image: kentik/get_kentik_interfaces
    networks:
      - kentik
    secrets:
      - kentik_api
      - harperdb
    labels:
      com.kentik.deployment: poc
      com.kentik.disc: "Recuring Get Inteface Metrics From Kentik"
      com.kentik.type: "pull data"
    environment:
        - KENTIK_URL=${KENTIK_URL}
        - KENTIK_HARPERDB_URL=${KENTIK_HARPERDB_URL}
        - KENTIK_HARPERDB_SCHEMA=${KENTIK_HARPERDB_SCHEMA}
        - KENTIK_HARPERDB_TABLE=${KENTIK_HARPERDB_TABLE}
        - KENTIK_QUERY_TIME_INCROMENT=${KENTIK_QUERY_TIME_INCROMENT}
        - KENTIK_QUERY_TIME_AMOUNT=${KENTIK_QUERY_TIME_AMOUNT}
    depends_on:
      - "harperdb"

volumes:
  harperdb_hdb:
    labels:
      com.kentik.deployment: poc
      com.kentik.disc: "HarperDB Store"
      com.kentik.type: database

networks:
  kentik:
    attachable: true
    labels:
      com.kentik.deployment: poc
      com.kentik.disc: "Kentik Overlay"

secrets:
  kentik_api:
    file: ./kentik_api.yml
  harperdb:
    file: ./harperdb.yml
